Repository Feed-B/frontend, pull requests merged in 2024-06, with the labels that each got.

#47 [Seunghoon] 버튼 공통컴포넌트 UI 수정
  app/_components/Button/Button.tsx
Labels: 💄 Design

#59 [Byeonghyeon] 댓글 페이지 생성
  app/_components/Button/DirectionButton.tsx
  app/_components/DropDown/DropDown.tsx
  app/_components/Header/Header.tsx
  app/_components/Header/HeaderDropDownBox.tsx
  app/_components/ProfileImage/ProfileImage.tsx
  app/_constants/MaxTextLength.ts
  app/_types/DropDownType.ts
  app/_utils/.gitkeep
  app/layout.tsx
  app/main/_components/SideBar/StackList.tsx
  app/main/layout.tsx
  app/mypage/_components/EditProfileModal/EditProfileJob.tsx
  app/project/[projectId]/_components/Comment/CommentCard.tsx
  app/project/[projectId]/_components/Comment/CommentCount.tsx
  app/project/[projectId]/_components/Comment/CommentProfile.tsx
  app/project/[projectId]/_components/Comment/TotalStar.tsx
  app/project/[projectId]/_components/CommnetModal/CommentModal.tsx
  app/project/[projectId]/_components/CommnetModal/ReflyCommentItem.tsx
  app/project/[projectId]/comments/[commentId]/_components/CommentDropbox.tsx
  app/project/[projectId]/comments/[commentId]/_components/CommentInput.tsx
  app/project/[projectId]/comments/[commentId]/_components/RatingBox.tsx
  app/project/[projectId]/comments/[commentId]/_components/ReflyCommentItem.tsx
  app/project/[projectId]/comments/[commentId]/_components/ReflyCommentList.tsx
  app/project/[projectId]/comments/[commentId]/page.tsx
  public/icons/blackArrowBottom.svg
  public/icons/blackArrowLeft.svg
  public/icons/blackArrowRight.svg
  public/icons/blackArrowTop.svg
  public/icons/grayStar.svg
  public/icons/reflyComment.svg
  public/icons/star2.svg
Labels: ✨ Feat, 💄 Design

#73 [Sohyun] Color 색상 변경
  tailwind.config.ts
Labels: 🔧 Chore

#74 [Yukyoung] intersectionObserver 로직 추가
  app/_components/ProjectList/ProjectCardInfo.tsx
  app/_components/ProjectList/ProjectList.tsx
  app/_hooks/useIntersectionObserver.ts
  package-lock.json
  package.json
Labels: ✨ Feat

#94 [Sohyun] httpClient url, header 부분 수정
  app/_apis/httpClient.ts
Labels: 🎨 Style

#99 [Sabibi] 프로젝트 작성 페이지 api 구현
  app/_apis/addProjectApi.ts
  app/_apis/httpClient.ts
  app/addproject/AddProject/AddProjectContainer.tsx
  app/addproject/_components/AddSection/AddSection.tsx
  app/addproject/_components/DropDown/DropDownBox.tsx
  app/addproject/_components/Input.tsx
  app/addproject/_components/ProjectImageBox/EmptyProjectImage.tsx
  app/addproject/_components/ProjectImageBox/ProjectImageBox.tsx
  app/addproject/_components/SkillStack/SelectSkillStack.tsx
  app/addproject/_components/SkillStack/SkillStackSection.tsx
  app/addproject/_components/TextArea.tsx
  app/addproject/_components/ThumbnailBox.tsx
  app/addproject/layout.tsx
  app/addproject/page.tsx
  public/icons/blackUpload.svg
Labels: ✨ Feat, 🎨 Style, 💄 Design

#105 [Byeonghyeon] 병합 충돌 해결
  app/_components/ProjectList/ProjectList.tsx
  app/main/_components/ProjectSection/ProjectSection.tsx
  app/profile/[userId]/_components/EditProfileModal/EditProfileModal.tsx
Labels: 🐛 Fix

#113 [Sohyun] HeaderToken 추가
  app/_apis/project.ts
  app/_constants/HeaderToken.ts
Labels: 🎨 Style

#121 [Byeonghyeon] 헤더 컴포넌트 프로필 조회 안되는 오류 해결
  app/_components/Header/HeaderDropDownBox.tsx
  app/_components/ProfileImage/ProfileImage.tsx
Labels: 🐛 Fix

#124 [Byeonghyeon] 프로필 컴포넌트 오류 해결
  app/_components/Header/HeaderDropDownBox.tsx
Labels: 🐛 Fix

#125 [YuKyoung] 직무 뱃지 한글로 나오도록 수정
  app/_components/JobBadge/JobBadge.tsx
  app/_constants/JobCategoryData.ts
  app/profile/[userId]/_components/Profile/Profile.tsx
Labels: 🎨 Style

#133 [YuKyoung] 프로필 수정 시, 헤더의 정보가 바로 반영되지 않던 문제 해결
  app/_components/Header/HeaderDropDownBox.tsx
  app/profile/[userId]/_components/MyPageContent.tsx
Labels: 🐛 Fix
