Repository Feed-B/frontend, pull requests merged in 2024-08, with the labels that each got.

#174 [YuKyoung] 좋아요 버튼 누를 때 로그인 여부 확인 로직 추가
  app/_components/WishButtonAndCount/WishButtonAndCount.tsx
Labels: ✨ Feat

#182 [YuKyoung] 반응형 분기 추가
  tailwind.config.ts
Labels: 🔧 Chore

#185 [Seunghoon] 드롭다운 박스 클릭 시 열리도록 수정
  app/_components/SignUpModal/SignUpDropdownBox.tsx
Labels: ♻️ Refactor

#181 [YuKyoung] 프로필 변경 후 반영되도록 수정
  app/profile/[userId]/_components/EditProfileModal/EditProfileModal.tsx
Labels: 🐛 Fix

#187 [Sohyun] 배포 브랜치 변경
  .github/workflows/git-push.yml
Labels: 🔧 Chore

#194 [Sabibi] 프로젝트 업로드 파일에서 revalidateTagAction 주석 해제
  app/addproject/AddProject/AddProjectContainer.tsx
Labels: ♻️ Refactor

#195 [Byeonghyeon] 좋아요 오류
  app/main/_components/ProjectSection/ProjectSection.tsx
  app/main/page.tsx
Labels: 🐛 Fix

#196 [Sohyun] 로그인 후 새로고침
  app/_components/LoginModal/LoginModal.tsx
Labels: 🐛 Fix

#202 [YuKyoung] 로그인하지 않았을 때 get요청 보내지 않도록 함
  app/_components/WishButtonAndCount/WishButtonAndCount.tsx
Labels: 🐛 Fix

#204 [Sohyun] 프로젝트, 댓글 삭제 오류 수정
  app/project/[projectId]/_components/Project/ProjectHeader.tsx
  app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
Labels: 🐛 Fix

#206 [Byeonghyeon] 프로젝트 삭제 오류 및 댓글 삭제 오류 해결
  app/project/[projectId]/_components/Project/ProjectHeader.tsx
  app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
Labels: 🐛 Fix

#207 [배포] 배포
  app/project/[projectId]/_components/Project/ProjectHeader.tsx
  app/project/[projectId]/comments/[ratingId]/_components/CommentDropbox.tsx
Labels: 🐛 Fix
